### ISSUE TITLE
[2Q2024] Single continuous variable values should show up in the dataset drawer

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#615]
DoD:
desired outcomes

1. The singleton values of numeric fields are displayed as they are submitted. The [example](https://cellxgene.cziscience.com/e/fb09f8c3-cb71-480d-8919-d8afd2670b97.cxg/) in the screenshot is submitted as `25.89`
2. The singleton values of numeric fields are displayed in the dataset drawer instead of the left panel, to mirror singleton values of string/boolean fields. The dataset drawer is accessed via the `i` in the upper right. The information under **Dataset** holds the singleton values.

---

Copied from #632 

Dataset values that do not very across observations show up in the dataset drawer in order to maximize analysis space in the main panels. Jason noticed a bug where continuous values are showing up in the left side panel, see the example for donor_BMI_at_collection [here](https://cellxgene.cziscience.com/e/fb09f8c3-cb71-480d-8919-d8afd2670b97.cxg/). 

The desired behavior is for this value to also show up in the dataset drawer.

---

Details

We have two examples of test datasets where continuous variables are showing up in the left side bar in Explorer from @jychien on the curation team. These values should show up in the dataset drawer.

A private test dataset: https://cellxgene.cziscience.com/e/7ecfdaed-d7ca-4e6e-8112-cb50bff8d79c.cxg/.  donor_BMI_at_collection is a numeric single value because this is a spatial assay.

![Screenshot 2023-05-23 at 3.44.12 PM.png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/799213ce-ad57-425f-bcbf-c65f9fe623bb)

This visium sample in this test collection has 25.89 for donor_BMI_at_collection. However, it is being displayed as a longer float. (there might be a typing issue with this as well. The 25.89 value should show up in the dataset drawer):
![Screenshot 2023-05-24 at 10.50.52 AM (1).png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/02055da4-d51a-419c-807a-9d032028d579)

**Comment by atarashansky** [comment]
This must not have been in the product specifications because we currently have no eng affordances to surface single-value continuous variable values. This affects both continuous metadata and boolean categorical metadata (which from a typing perspective is effectively continuous).

With boolean data, it's an easy workaround (in #656) because we know there are only ever going to be 2 categories max. With continuous data, this same workaround will _not_ work because it will be too computationally intensive on application startup to count the number of unique continuous values for every single continuous metadata.

To get this working, it would require work on the CXG converter to add a bit of metadata that would flag continuous data as single-valued. This would then require a migration of all CXGs to update existing explorer instances, which expands the scope of the eng work required to complete this ticket.

@signechambers1 @dsadgat Can you reassess the priority of this ticket given the above information?

**Comment by jahilton** [comment]
Sorry, didn't realize that this had been closed...
Still think this bug should be fixed, especially as we are prioritizing Slide-seq & Visium data where we can expect a lot more singleton values for metadata (as most Datasets will represent a single tissue section from a single donor).

**Comment by tihuan** [comment]
Per @niknak33 , re-opening this ticket and will get this fixed before the spatial mode launch in June 🚀 

Thanks @jahilton 🎉 !

**Comment by tihuan** [comment]
Also @jahilton and @atarashansky for someone who's not familiar with Explorer, can you help me understand the outcome we wanna see again?

For example, in this visium dataset example, it sounds like we want donor_BMI_at_collection to show 25.89 instead of the long float?

And where's the dataset drawer again and how should this value show up in it? 

![Screenshot 2023-05-24 at 10.50.52 AM (1).png](https://images.zenhubusercontent.com/5f47df0cc52f8855d9f0c5d5/02055da4-d51a-419c-807a-9d032028d579)

SORRY I'm super unfamiliar with Explorer 😂 

CC: @seve in case you can help me out here!

**Comment by jahilton** [comment]
desired outcomes

1. The singleton values of numeric fields are displayed as they are submitted. The [example](https://cellxgene.cziscience.com/e/fb09f8c3-cb71-480d-8919-d8afd2670b97.cxg/) in the screenshot is submitted as `25.89`
2. The singleton values of numeric fields are displayed in the dataset drawer instead of the left panel, to mirror singleton values of string/boolean fields. The dataset drawer is accessed via the `i` in the upper right. The information under **Dataset** holds the singleton values.

**Comment by tihuan** [comment]
Ah thanks so much for the writeup, Jason 🙏 That looks super good! I'll copy it to the ticket description!

**Comment by tihuan** [comment]
Waiting for @seve to double confirm if it's an 8 point effort

**Comment by seve** [comment]
temp assigning to myself while I look into the ticket

**Comment by tihuan** [comment]
@seve please kindly help document the FE only approach here and lower the point to 3 for now. Thanks so much!

Probably still worth keeping the BE approach for future reference too!

**Comment by atarashansky** [comment]
Oh, a frontend-only approach to shunt data over into the drawer if it's single-valued is much smarter than what I was thinking of :P

**Comment by tihuan** [comment]
The backend approach definitely has its benefits though! Which is why we still want to keep the BE approach in the pocket 👍

**Comment by tihuan** [comment]
bumped to P0 now that we're in Q2 and this is a must have!
