### ISSUE TITLE
Update Explorer {column}_colors functionality to use term fields as well as label fields

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#643]
See [{column}_colors](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#column_colors). 

Currently, curators, for example, will rename <name>_ontology_term_id_colors to <name>_colors (for example, tissue_ontology_term_id_colors to tissue_colors). But there are datasets that do not have renames because the _colors behavior was previously undefined and it took awhile for the curators to figure out that Explorer only used the label fields (tissues).

With schema 4, color annotations with labels will be invalid. We want to update Explorer so that we can continue supporting the current use case of label fields (tissue_colors), as well as support the future use case of term fields (tissue_ontology_term_id_colors). Allowing backwards compatibility will make this schema 4 downstream change smoother and not necessitate coordinating a prod deploy with the schema 4 release.

[Relevant slack thread](https://czi-sci.slack.com/archives/C024HCSH9PT/p1689787135274349)

**Comment by brianraymor** [comment]
> To allow compatibility with both ways, we want to look for colors in both the term fields as well as the label fields (ex: check both "tissue_colors" and "tissue_ontology_term_ids")

The schema prohibits `tissue_colors`, so validation must fail. Explorer should never "see" such cases.

The mitigation is that failures will be logged during the dry-run for schema 4 migration. The curators can then script renames (unless there are naming collisions - both `tissue_colors` and `tissue_ontology_term_id_colors`. And I expect that you'll see failures related to the color values since schema 4 only supports a subset of the original possibilities.

CC: @nayib-jose-gloria @signechambers1

**Comment by joyceyan** [comment]
@brianraymor In terms of how this is implemented, we actually plan to update the CXG converter to generate the colors metadata to use label fields, since explorer uses label fields in the UI--ontology terms are not displayed. So regardless of whether you're passing in term fields or label fields, the colors metadata would be generated like this:
```
            "assay": {
                "10x 3' v2": "#ffb6c1",
                "10x 3' v3": "#ffc0cb"
            },
            "cell_type": {
                "mature B cell": "#ffb6c1",
                "plasma cell": "#ffc0cb"
            },
            "development_stage": {
                "human adult stage": "#ff69b4",
                "mature stage": "#ffc0cb"
            },
            "donor_id": {
                "C41": "#ff0000",
                "C58": "#ffa500",
                "C70": "#ffff00",
                "C72": "#008000"
            },
            "sex": {
                "female": "#ffc0cb",
                "male": "#0000ff"
            },
            "suspension_type": {
                "cell": "#0000ff",
                "nucleus": "#800080"
            }
```
rather than something like this
```
        expected_term_colors = {
            "assay_ontology_term_id": {
                "EFO:0009899": "#ffb6c1",
                "EFO:0009922": "#ffc0cb"
            },
            "cell_type_ontology_term_id": {
                "CL:0000785": "#ffb6c1",
                "CL:0000786": "#ffc0cb"
            },
            "development_stage_ontology_term_id": {
                "HsapDv:0000087": "#ff69b4",
                "HsapDv:0000204": "#ffc0cb"
            },
            "donor_id": {
                "C41": "#ff0000",
                "C58": "#ffa500",
                "C70": "#ffff00",
                "C72": "#008000"
            },
            "sex_ontology_term_id": {
                "PATO:0000383": "#ffc0cb",
                "PATO:0000384": "#0000ff"
            },
            "suspension_type": {
                "cell": "#0000ff",
                "nucleus": "#800080"
            }
        }
```
The benefit of providing backwards compatibility for usage of label fields as well as term fields is that we'll make sure that Explorer colors don't break between when we work on this change and when schema 4 is launched (or necessitate coordinating a prod deploy with the schema 4 launch). We can deploy our changes to the CXG convertor in data portal, and have it support both how curators currently annotate their colors fields with label terms, as well as how we plan to restrict colors annotations in schema 4 with term fields. I don't see any downsides to taking a more lenient approach in how we parse the color metadata for Explorer purposes.

**Comment by atarashansky** [comment]
[This PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/6023) adds a safety net in case the H5AD contains colors for any ontology term ID metadata column.

However, if the schema guarantees that the CXG converter will never encounter such a situation, then we don't need to do anything on the converter side of things.

@brianraymor Does the validator currently fail when encountering something like `assay_ontology_term_id_colors`? If yes, then nothing needs to be done for this work. If no, then we just need to add that check to the validator and can then close out this ticket.

**Comment by brianraymor** [comment]
> Does the validator currently fail when encountering something like assay_ontology_term_id_colors?

_colors did not exist as a supported field in Schema 3. 

Schema 4 validation must fail `assay_colors`(label fields) in a dataset per Viz requirements:

The following columns that are annotated by CELLxGENE Discover MUST NOT be specified as {column}:

assay
cell_type
development_stage
disease
organism
self_reported_ethnicity
sex
tissue

It's fine if you're simply internally rewriting `assay_ontology_term_id` to `assay` during CXG conversion based on the earlier implementation. But CXG conversion should never receive "assay_colors" from the ingestion pipeline because it's invalid.

**Comment by joyceyan** [comment]
Gotcha - I think we're aligned then. This ticket was originally written to state that Explorer should show colors annotated as `{column}_ontology_term_id_colors`, and after discussing with @signechambers1 we agreed it made more sense to update Explorer to support both `{column}_colors` and `{column}_ontology_term_id_colors` so that we could smoothly support the schema 4 migration. I can update the ticket to make it clear that this is done purely for compatibility purposes, not because we expect to receive datasets that may have both term fields and label fields.

**Comment by atarashansky** [comment]
Ahh, I understand now. Thanks for the clarification, @brianraymor! Then we can go ahead with the aforementioned PR to internally rewrite "assay_ontology_term_id_colors" to "assay_colors" and add a check to the validator to fail "assay_colors".

**Comment by brianraymor** [comment]
> add a check to the validator to fail "assay_colors".

That should already be implemented per - https://github.com/chanzuckerberg/single-cell-curation/issues/513 - which enforces the schema requirements.

**Comment by joyceyan** [comment]
Yep, the check has already been added to the validator.
