### ISSUE TITLE
Enable rendering full resolution image

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#800]
Context:
The MVP only renders ~low-res~ (UPDATE (2/29): no low-res support) and high-res, this ticket will enable rendering full res image in the spatial mode

DoD:
1. A user is now able to select full res in embedding mode option
2. Export PNG still works
3. Add e2e tests

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/800?planning-poker) with Zenhub @kaloster @seve

**Comment by tihuan** [comment]
My estimate assumes that tweaking the scaleFactor won't take more than a few hours, or maybe scaleFactor is not even needed for full res?

**Comment by brianraymor** [comment]
> or maybe scaleFactor is not even needed for full res?

There is no scalefactor for fullres, because the embedding is already fullres. 

This was documented in the implementation notes that I shared with you on [slack](https://czi-sci.slack.com/archives/C02TSE92DBM/p1709144995250509?thread_ts=1709077005.266549&cid=C02TSE92DBM):

If uns['spatial'][library_id]['images']['fullres'] is present, then CELLxGENE Explorer MUST add a selector item named "spatial_FullRes_Map" and **MUST NOT scale the full resolution embedding**.

**Comment by brianraymor** [comment]
> The MVP only renders **low-res** and high-res, this ticket will enable rendering full res image in the spatial mode

FYI - The schema does not support lowres, only highres (required) and fullres (optional).

**Comment by tihuan** [comment]
Ah thanks for confirming, Brian! Then hopefully adding full res support will be a lot less work than estimated 🤞

And appreciate you pointing out the low-res stuff. I'll update the ticket accordingly! (Sorry I haven't checked the schema yet 😆)

**Comment by tihuan** [comment]
Closing, since we're implementing deep zooming
