### ISSUE TITLE
Previous (cached?) dataset is opened in explorer after revision

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-explorer#84]
This occurs on Chrome/MacOS.

I explored a CXG in a published collection.

In a revision, I updated the dataset for that CXG with another dataset to ensure that the title, categories, clustering would be completely different as a visual clue. I published the revision and then explored the CXG again. I was still seeing the previous dataset based on its title:

https://images.zenhubusercontent.com/397736859/d15dbaa0-e9cf-4903-8998-e737788073bc/screen_recording_2021_09_23_at_2_15_10_pm.mov

Disabling the browser cache in DevTools and refreshing the page resolves the issue.

**Comment by brianraymor** [comment]
The `public` and `no-cache` directives in the cache-control response headers appear to be in conflict with the `no-store` directive? 

cache-control: public, max-age=0, no-store, no-cache, must-revalidate

instead of:

cache-control: max-age=0, no-store

**Comment by tihuan** [comment]
Staging shows `no-store` only now!

Thank you!![Screen Shot 2021-09-24 at 12.22.30 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/97ea973b-17b1-4fdc-8126-62ac930648fe)

**Comment by tihuan** [comment]
Can we also update Jenny on when we think we will be able to fix the cache issue please?

Slack thread: https://czi-sci.slack.com/archives/C024HCSH9PT/p1632523415243200?thread_ts=1632511324.238100&cid=C024HCSH9PT

Thank you!

**Comment by atolopko-czi** [comment]
@tihuan has provided this workaround fix, along with reproducibility steps, which can be used to test proposed fixes:

By changing the corresponding API handlers to @cache_control(public=True, max_age=0) + ETag, the behavior we see should be:

1. FE hits GET /config
2. CloudFront forwards the GET request to BE
3. BE returns JSON with headers public, max-age=0
4. CloudFront returns the JSON response to FE
5. FE refreshes the page and makes another GET /config call
6. Browser sees max-age=0, sends GET /config along with If-None-Match: Etag value to CloudFront
7. CloudFront sees If-None-Match, thus forwarding request’s ETag to BE server
8. BE server checks ETag with its latest resource’s ETag, if the same, returns 304, otherwise return 200 and the new JSON content back to CloudFront
9. CloudfFront faithfully returns whatever BE gives it back to FE
10. FE sees 304, uses existing cached content, else download the new JSON content!

Reproduce/Test:
1. Create a revision
1. Replace a dataset
1. Publish the revision
1. Check the dataset Explorer link <--- BUG: this step will still return the old dataset’s data, because of the 1 week caching

**Comment by atolopko-czi** [comment]
Seamless selector caching bug now has its own specific story: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/154.  [Larger caching design fixes](https://docs.google.com/document/d/1T3KrQkpcK5eS7-lZdvl3fsrDFr6d7fKvmo9rg-L2gIE/edit#) are planned.

**Comment by brianraymor** [comment]
Still easily reproduced:
https://images.zenhubusercontent.com/397736859/1945e642-6bb1-4ec0-b2a1-3dc0e2484ac4/screen_recording_2021_11_05_at_12_00_15_pm.mov
