### ISSUE TITLE
feat(side by side embedding): complex embedding feature parity

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#925]
This issue captures the more complex features that are needed in the side panel in order to match the feature set found in the main graph.

- [ ]  Lasso in panel
  - [ ] Need to create a separate reducer for the smaller lasso (this is to ensure that lassos aren't cancelled across the two)|
  - [ ] Fix lasso where the two lasso layers overlap
  - [ ] Lasso should reset when changing embeddings ([legacy handling](https://github.com/chanzuckerberg/single-cell-explorer/pull/964#discussion_r1626756374))
- [ ] Camera
  - [ ] When starting a camera action in one graph, lock the mouse actions to the origin graph

**Comment by seve** [comment]
@niknak33 are we okay to reset zoom and/or lasso state if we swap the embeddings in the main and panel views?

**Comment by niknak33** [comment]
That's fine Seve - Thank you.

**Comment by tihuan** [comment]
For resize - currently we're attaching a "resize" event listener on `window`, which is inefficient (since the canvas element doesn't necessary resize when the window resizes) and won't work well that now the Graph component is used in both the main and side panels.

Perhaps we should use `ResizeObserver` to observe `Graph.props.viewportRef` to capture the resize event instead?

**Comment by tihuan** [comment]
@seve I'll unassign myself from this one since I didn't get to work on it this week and I'll be out for a week 🙏

Happy to pick it back up if it's not worked on yet by the time I get back! Thank you!

**Comment by tihuan** [comment]
implemented in the feature branch already
